# Generated by Django 4.0.5 on 2022-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('movie_type', models.CharField(choices=[('', 'Select movie type'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Crime & Gangster', 'Crime & Gangster'), ('Drama', 'Drama')], max_length=100)),
                ('about_us', models.CharField(max_length=255)),
                ('director', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('', 'Select language'), ('ENGLISH', 'English'), ('Gujarati', 'Gujarati'), ('BENGALI', 'Bengali'), ('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=10)),
                ('run_length', models.IntegerField(help_text='Enter run length in minutes')),
                ('trailer', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_no_of_screen', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
