# Generated by Django 4.0.5 on 2022-08-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('movie_type', models.CharField(choices=[('', 'Select type'), ('Action Films', 'Action Films'), ('Comedy Films', 'Comedy Films'), ('Crime & Gangster Films', 'Crime & Gangster Films'), ('Drama Films', 'Drama Films')], max_length=100)),
                ('director', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('', 'Select language'), ('ENGLISH', 'English'), ('BENGALI', 'Bengali'), ('HINDI', 'Hindi'), ('TAMIL', 'Tamil'), ('TELUGU', 'Telugu')], max_length=10)),
                ('run_length', models.IntegerField(help_text='Enter run length in minutes')),
                ('trailer', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
