# Generated by Django 4.0.5 on 2022-08-26 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='theatre_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Api.theatre'),
            preserve_default=False,
        ),
    ]
