# Generated by Django 4.0.5 on 2022-08-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='movie',
        #     name='image',
        #     field=models.FileField(upload_to=''),
        # ),
    ]
