# Generated by Django 4.0.5 on 2022-08-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_screen_theatre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.movie')),
                ('screen_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.screen')),
                ('theatre_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.theatre')),
            ],
        ),
    ]
