# Generated by Django 4.0.5 on 2022-08-25 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_theatre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='screen_name',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('', 'Select movie type'), ('Action Films', 'Action Films'), ('Comedy Films', 'Comedy Films'), ('Crime & Gangster Films', 'Crime & Gangster Films'), ('Drama Films', 'Drama Films')], max_length=100),
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.theatre')),
            ],
        ),
    ]
