# Generated by Django 4.0.5 on 2022-08-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_movieshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreScreenSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=4)),
                ('screen_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.screen')),
                ('theatre_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.theatre')),
            ],
        ),
    ]
