# Generated by Django 4.0.5 on 2022-08-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_remove_theatre_screen_name_alter_movie_movie_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='start_time',
            field=models.IntegerField(help_text='Enter run length in minutes'),
        ),
    ]
