# Generated by Django 4.0.5 on 2022-08-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_estimation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estimation',
        ),
    ]
