# Generated by Django 4.0.5 on 2022-08-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_delete_estimation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheatreScreenSeat',
            new_name='TheatreSeat',
        ),
    ]
