# Generated by Django 4.0.5 on 2022-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_rename_theatrescreenseat_theatreseat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='total_no_of_screen',
        ),
        migrations.RemoveField(
            model_name='theatreseat',
            name='seat',
        ),
        migrations.AddField(
            model_name='screen',
            name='screen_no',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
