# Generated by Django 4.0.5 on 2022-08-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_remove_screen_total_no_of_screen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatreseat',
            name='col',
            field=models.IntegerField(default=20, max_length=2),
        ),
        migrations.AddField(
            model_name='theatreseat',
            name='row',
            field=models.IntegerField(default=12, max_length=2),
        ),
        migrations.AddField(
            model_name='theatreseat',
            name='seat',
            field=models.CharField(choices=[('A1', 'A1'), ('An', 'An')], default='An', max_length=1000, unique=True),
        ),
    ]
