# Generated by Django 4.0.5 on 2022-08-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_theatreseat_screen_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatreseat',
            name='seat',
            field=models.CharField(choices=[(models.IntegerField(default=12, max_length=2), models.IntegerField(default=20, max_length=2))], default='An', max_length=1000, unique=True),
        ),
    ]
