# Generated by Django 4.0.5 on 2022-08-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_theatreseat_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatreseat',
            name='seat',
            field=models.CharField(default='An', max_length=1000, unique=True),
        ),
    ]
