# Generated by Django 4.0.5 on 2022-08-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_alter_theatreseat_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatreseat',
            name='seat',
            field=models.CharField(blank=True, choices=[(models.IntegerField(default=12, max_length=2), models.IntegerField(default=20, max_length=2))], max_length=1000),
        ),
    ]
