# Generated by Django 4.0.5 on 2022-08-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_remove_theatreseat_seat_alter_theatreseat_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatreseat',
            name='seat',
            field=models.CharField(auto_created=True, default='', max_length=1000),
            preserve_default=False,
        ),
    ]
