# Generated by Django 4.0.5 on 2022-09-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_remove_bookseat_seat_remove_theatreseat_col_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseat',
            name='book_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.theatreseat'),
        ),
    ]
