# Generated by Django 4.0.5 on 2022-09-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0021_alter_bookseat_seat_alter_bookseat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='run_length',
            field=models.IntegerField(help_text='Etern run length in minutes'),
        ),
    ]
